# Generated by Django 2.2.6 on 2019-11-29 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191110_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='apellidos',
            field=models.CharField(max_length=150, verbose_name='Apellido '),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicacion'),
        ),
    ]
